# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/PROJECT/3bitadder/3bitadder.cache/wt [current_project]
set_property parent.project_path E:/PROJECT/3bitadder/3bitadder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib E:/PROJECT/3bitadder/3bitadder.srcs/sources_1/new/adder.vhd
synth_design -top adder -part xc7a35tcpg236-1
write_checkpoint -noxdef adder.dcp
catch { report_utilization -file adder_utilization_synth.rpt -pb adder_utilization_synth.pb }
